config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :customers #add the routes for registration, login and logout - rails generate devise Customer
  resources :orders
  resources :customers
  resources :products, only: [:show, :index]
  resource :shopping_cart
  resource :stores
  resource :shipping_detail
  resource :charts
  root "products#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
	skip_before_action :verify_authenticity_token

	def create
		@product_id= params[:id] 
		#to capture session details - hidden values
		@shopping_cart = Product.where(id: session[:shopping_cart])

		if session.key?(:shopping_cart)              
			session[:shopping_cart] << params[:id]
		else
			session[:shopping_cart] = []
			session[:shopping_cart] << params[:id]
		end 
		render :show
	end

	def show
		@shopping_cart = Product.where(id: session[:shopping_cart])
	end 

	def destroy
		session[:shopping_cart].delete(params[:id])
		redirect_to action: "show"
	end

end 

app/views/shopping_carts/show.html.erb
<body>	
	<h1>Shopping Cart</h1>

<table>
  <thead>
    <tr>
      <th>Product ID</th>
      <th>Product name</th>
      <th>Brand</th>
      <th>Category</th>
      <th>Price</th>
      <th>Remove this item</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>

	<% @shopping_cart.each do |product| %>
	<tr>
		<td>td<%= product.id %></td>
		<td><%= product.product_name %></td>
		<td><%= product.brand %></td>
		<td><%= product.product_category %></td>
		<td>£<%= product.price %></td>
		<td><%= link_to 'Remove item', shopping_cart_path(id: product.id), method:"delete"%></td>
	</tr>
	<% end %>
</tbody>
</table>

<%= link_to 'Check Out', stores_path %>
<%= link_to 'Back to Shopping', products_path %>
</body>

<p>Have a look at our Furniture for exciting Christmas/New Year offers upto 50%</p>