config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :customers #add the routes for registration, login and logout - rails generate devise Customer
  resources :orders
  resources :customers
  resources :products, only: [:show, :index]
  resource :shopping_cart
  resource :stores
  resource :shipping_detail
  resource :charts
  root "products#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/shipping_detail.rb
class ShippingDetail < ApplicationRecord
	validates :address, presence: true
	validates :phone, presence: true
	validates :postal_code, presence: true
	validates :country, presence: true
	
end

app/controllers/shipping_details_controller.rb
class ShippingDetailsController < ApplicationController
	before_action :authenticate_customer!
	
	def new
		@shipping_detail = ShippingDetail.new
		unless current_customer.store
			redirect_to "/stores/index"
		end 
	end

	def create
		ShippingDetail.create!(shipping_params)
		render "payments/new"
	end

	def shipping_params
		params.require(:shipping_detail).permit(:address, :country, :postal_code, :phone)
	end
end

app/views/shipping_details/_form.html.erb
    <link 
    rel="stylesheet" 
    href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
    integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
    crossorigin=""
    />
      
    <script
    src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
    integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
    crossorigin="">
    </script>

<%= form_with(model: shipping_detail, url: shipping_detail_path,local: true) do |form| %>
  <% if shipping_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shipping_detail.errors.count, "error") %> prohibited this shipping detail from being saved:</h2>

      <ul>
        <% shipping_detail.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div class = "container">
    
    <div class = "row">       

      <div class="field">
        <%= form.label :address %>
        <%= form.text_field :address, required: true %>
      </div>

      <div class="field">
        <%= form.label :country %>
        <%= form.text_area :country, required: true %>
      </div>

      <div class="field">
        <%= form.label :postal_code %>
        <%= form.text_field :postal_code, required: true %>
      </div>

      <div class="field">
        <%= form.label :phone %>
        <%= form.text_field :phone, required: true %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
      <% end %>

    </div>
</div>


<h3>You can check the live location of your selected store by refreshing this page for confirmation</h3>

app/views/shipping_details/new.html.erb
<h1>Shipping Details</h1>
<!-----Displays the map of each store location ----->
<%= render 'form', shipping_detail: @shipping_detail %>


   <link 
    rel="stylesheet" 
    href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
    integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
    crossorigin=""
    />
      
    <script
    src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
    integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
    crossorigin="">
    </script>

 <div id="mapid"></div>

<script> 
    $('document').ready(function(){
        var mymap = L.map('mapid').setView([55.010, -3.010], 5);     
          
    L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
    attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
    maxZoom: 18,
    id: 'mapbox/streets-v11',
    tileSize: 512,
    zoomOffset: -1,
    accessToken: 'pk.eyJ1IjoidDE1aHMxOSIsImEiOiJja2dyaGx2amQwZjBtMnhxdzBmd2loZ3F5In0.NemiDxQl-m-_CBtwLT4R7Q'
    }).addTo(mymap);
       
   
    var marker = L.marker([<%= current_customer.store.latitude %>, <%= current_customer.store.longitude %>]).addTo(mymap);
});
</script>

<%= link_to 'Back to Shopping Cart to add more products', shopping_cart_path %>